import type { PrismaClient, ProductFieldKind, ProductTypeIdentity } from '../generated/client';

const TYPES: Array<{id:string;identity:ProductTypeIdentity;nameAr:string;nameEn:string;description:string;fields:Array<{key:string;label:string;kind:ProductFieldKind;required:boolean}>}> = [
  {id:'20000000-0000-4000-8000-000000000001',identity:'PROFESSIONAL_PROGRAM',nameAr:'برنامج مهني',nameEn:'Professional Program',description:'برنامج مهني يدعم الدفعات',fields:[{key:'duration',label:'المدة',kind:'NUMBER',required:true},{key:'numberOfTerms',label:'عدد الفصول',kind:'NUMBER',required:true},{key:'internshipIncluded',label:'التدريب العملي',kind:'BOOLEAN',required:false},{key:'trainingIncluded',label:'التدريب',kind:'BOOLEAN',required:false},{key:'finalProjectRequired',label:'مشروع التخرج',kind:'BOOLEAN',required:false}]},
  {id:'20000000-0000-4000-8000-000000000002',identity:'PROFESSIONAL_DIPLOMA',nameAr:'دبلومة مهنية',nameEn:'Professional Diploma',description:'دبلومة مهنية بجلسات محددة',fields:[{key:'duration',label:'المدة',kind:'NUMBER',required:true},{key:'numberOfSessions',label:'عدد الجلسات',kind:'NUMBER',required:true},{key:'trainingIncluded',label:'التدريب',kind:'BOOLEAN',required:false}]},
  {id:'20000000-0000-4000-8000-000000000003',identity:'TRAINING_COURSE',nameAr:'دورة تدريبية',nameEn:'Training Course',description:'دورة تدريبية بمدرب معتمد',fields:[{key:'numberOfHours',label:'عدد الساعات',kind:'NUMBER',required:true},{key:'numberOfSessions',label:'عدد الجلسات',kind:'NUMBER',required:true},{key:'instructorEmployeeId',label:'المدرب',kind:'REFERENCE',required:true}]},
];

export async function seedAcademicCatalog(prisma:PrismaClient):Promise<void>{
  for(const type of TYPES){const row=await prisma.productType.upsert({where:{identity:type.identity},update:{nameAr:type.nameAr,nameEn:type.nameEn,description:type.description},create:{id:type.id,identity:type.identity,nameAr:type.nameAr,nameEn:type.nameEn,description:type.description}});await prisma.productTypeField.deleteMany({where:{productTypeId:row.id}});await prisma.productTypeField.createMany({data:type.fields.map((field,index)=>({...field,productTypeId:row.id,position:index+1}))});}
  const organization=await prisma.organization.findUniqueOrThrow({where:{singletonKey:'PRIMARY'}});
  const group=await prisma.lookupGroup.upsert({where:{organizationId_code:{organizationId:organization.id,code:'business-categories'}},update:{name:'تصنيفات الأعمال'},create:{organizationId:organization.id,code:'business-categories',name:'تصنيفات الأعمال',normalizedName:'تصنيفات الاعمال'}});
  await prisma.lookupValue.createMany({data:[['engineering','الهندسة'],['medical','المجال الطبي'],['it','تقنية المعلومات'],['business','إدارة الأعمال']].map(([code,name],index)=>({lookupGroupId:group.id,code,name,normalizedName:name,sortOrder:(index+1)*10})),skipDuplicates:true});
}
