export interface PermissionSeed {
  key: string;
  moduleKey: string;
  actionKey: string;
  label: string;
  description: string;
  displayOrder: number;
}

const keys = [
  'dashboard.view',
  'settings.view',
  'settings.create',
  'settings.organization.view',
  'settings.organization.update',
  'settings.branches.view',
  'settings.branches.create',
  'settings.branches.update',
  'settings.departments.view',
  'settings.departments.create',
  'settings.departments.update',
  'settings.academicYears.view',
  'settings.academicYears.create',
  'settings.academicYears.update',
  'settings.academicTerms.view',
  'settings.academicTerms.create',
  'settings.academicTerms.update',
  'settings.users.view',
  'settings.users.create',
  'settings.users.update',
  'settings.documentRequirements.view',
  'settings.documentRequirements.update',
  'settings.roles.view',
  'settings.roles.create',
  'settings.roles.update',
  'settings.permissions.view',
  'settings.permissions.update',
  'settings.general.view',
  'settings.general.update',
  'settings.lookups.view',
  'settings.lookups.create',
  'settings.lookups.update',
  'catalog.view',
  'catalog.products.view',
  'catalog.products.create',
  'catalog.products.update',
  'catalog.products.activate',
  'catalog.products.archive',
  'catalog.types.view',
  'catalog.types.update',
  'catalog.types.activate',
  'catalog.types.archive',
  'catalog.categories.view',
  'catalog.categories.create',
  'catalog.categories.update',
  'catalog.categories.activate',
  'catalog.categories.archive',
  'catalog.academic.manage',
  'catalog.pricing.manage',
  'catalog.availability.manage',
  'catalog.content.manage',
  'catalog.media.manage',
  'batches.view',
  'batches.create',
  'batches.update',
  'batches.export',
  'batches.capacity.manage',
  'batches.pricing.manage',
  'batches.branches.manage',
  'batches.registration.open',
  'batches.registration.close',
  'batches.registration.correct',
  'batches.study.start',
  'batches.graduate',
  'batches.archive',
  'admissions.view',
  'admissions.create',
  'admissions.update',
  'admissions.archive',
  'admissions.export',
  'admissions.assign',
  'admissions.academic.manage',
  'admissions.finance.view',
  'admissions.finance.manage',
  'admissions.documents.view',
  'admissions.documents.manage',
  'admissions.documents.verify',
  'admissions.submit',
  'admissions.review',
  'admissions.approve',
  'admissions.reject',
  'admissions.return',
  'admissions.enrollment-readiness',
  'students.view',
  'students.update',
  'students.archive',
  'students.activate',
  'students.status.manage',
  'students.status.correct',
  'students.export',
  'students.enrollments.view',
  'students.documents.view',
  'students.documents.manage',
  'students.notes.view',
  'students.notes.manage',
  'students.timeline.view',
  'students.finance.view',
  'students.intake',
  'finance.view',
  'finance.invoices.view',
  'finance.invoices.create',
  'finance.invoices.update',
  'finance.invoices.issue',
  'finance.invoices.cancel',
  'finance.installments.manage',
  'finance.payments.view',
  'finance.payments.record',
  'finance.discounts.approve',
  'finance.scholarships.approve',
  'finance.refunds.view',
  'finance.refunds.record',
  'finance.refunds.approve',
  'finance.timeline.view',
  'finance.export',
  'accounting.view',
  'accounting.dashboard.view',
  'accounting.requests.view',
  'accounting.requests.create',
  'accounting.requests.update',
  'accounting.requests.submit',
  'accounting.requests.review',
  'accounting.requests.decide',
  'accounting.requests.markPaid',
  'accounting.requests.cancel',
  'accounting.attachments.manage',
  'accounting.comments.add',
  'accounting.categories.view',
  'accounting.categories.manage',
  'accounting.history.view',
  'accounting.export',
  'tickets.view.assigned',
  'tickets.view.team',
  'tickets.view.all',
  'tickets.create',
  'tickets.edit',
  'tickets.assign.team',
  'tickets.assign.employee',
  'tickets.reassign',
  'tickets.change.status',
  'tickets.change.priority',
  'tickets.archive',
  'tickets.comment',
  'tickets.attach.files',
  'tickets.restore',
  'tickets.delete',
  'inbox.view.all',
  'inbox.view.team',
  'inbox.view.assigned',
  'inbox.assign.employee',
  'inbox.assign.team',
  'inbox.reassign',
  'inbox.reply',
  'inbox.change.status',
  'inbox.manage.tags',
  'inbox.manage.notes',
  'inbox.archive',
  'inbox.delete',
  'inbox.restore',
] as const;

const admissionsDescriptions: Readonly<Record<string, string>> = {
  'admissions.view': 'View admission lists and details',
  'admissions.create': 'Create draft admissions',
  'admissions.update': 'Update editable admission data',
  'admissions.archive': 'Archive admissions with a reason',
  'admissions.export': 'Export admission lists',
  'admissions.assign': 'Assign admissions staff and branches',
  'admissions.academic.manage': 'Change academic selection',
  'admissions.finance.view': 'View admission financial snapshots',
  'admissions.finance.manage': 'Revise admission financial snapshots',
  'admissions.documents.view': 'View admission documents',
  'admissions.documents.manage':
    'Upload, replace, and withdraw admission documents',
  'admissions.documents.verify': 'Verify or reject admission documents',
  'admissions.submit': 'Submit draft admissions',
  'admissions.review': 'Review submitted admissions',
  'admissions.approve': 'Approve eligible admissions',
  'admissions.reject': 'Reject admissions with a reason',
  'admissions.return': 'Return admissions to draft with a reason',
  'admissions.enrollment-readiness':
    'View approved admission enrollment readiness',
};

const definitions = keys.map((key) => [key, `صلاحية ${key}`] as const);

export const PERMISSION_CATALOG: readonly PermissionSeed[] = definitions.map(
  ([key, label], displayOrder) => {
    const parts = key.split('.');
    return {
      key,
      moduleKey: parts[0],
      actionKey: parts.at(-1) ?? key,
      label,
      description: admissionsDescriptions[key] ?? label,
      displayOrder,
    };
  },
);
