export interface PermissionSeed {
  key: string;
  moduleKey: string;
  actionKey: string;
  label: string;
  description: string;
  displayOrder: number;
}

const keys = [
  'dashboard.view',
  'settings.view',
  'settings.create',
  'settings.organization.view',
  'settings.organization.update',
  'settings.users.view',
  'settings.users.create',
  'settings.users.update',
  'settings.roles.view',
  'settings.roles.create',
  'settings.roles.update',
  'settings.permissions.view',
  'settings.permissions.update',
  'settings.general.view',
  'settings.general.update',
  'settings.teams.view',
  'settings.teams.create',
  'settings.teams.update',
  'settings.tags.view',
  'settings.tags.create',
  'settings.tags.update',
  'settings.branches.view',
  'settings.branches.create',
  'settings.branches.update',
  'settings.lookups.view',
  'settings.lookups.create',
  'settings.lookups.update',
  'tickets.view.assigned',
  'tickets.view.team',
  'tickets.view.all',
  'tickets.create',
  'tickets.edit',
  'tickets.assign.team',
  'tickets.assign.employee',
  'tickets.reassign',
  'tickets.change.status',
  'tickets.change.priority',
  'tickets.archive',
  'tickets.comment',
  'tickets.attach.files',
  'tickets.restore',
  'tickets.delete',
  'inbox.view.all',
  'inbox.view.team',
  'inbox.view.assigned',
  'inbox.assign.employee',
  'inbox.assign.team',
  'inbox.reassign',
  'inbox.reply',
  'inbox.change.status',
  'inbox.manage.tags',
  'inbox.manage.notes',
  'inbox.archive',
  'inbox.delete',
  'inbox.restore',
  'contacts.view',
  'contacts.create',
  'contacts.update',
  'contacts.delete',
  'contacts.import',
  'contacts.export',
  'contacts.groups.manage',
  'contacts.fields.manage',
  'contacts.notes.manage',
  'pipeline.view',
  'pipeline.create',
  'pipeline.update',
  'pipeline.move',
  'pipeline.assign',
  'pipeline.manage',
  'campaigns.view',
  'campaigns.create',
  'campaigns.update',
  'campaigns.delete',
  'campaigns.launch',
  'campaigns.templates.sync',
  'ai.settings.view',
  'ai.settings.manage',
  'ai.knowledge.view',
  'ai.knowledge.manage',
  'ai.runs.view',
  'inbox.ai.control',
] as const;

const definitions = keys.map((key) => [key, `صلاحية ${key}`] as const);

export const PERMISSION_CATALOG: readonly PermissionSeed[] = definitions.map(
  ([key, label], displayOrder) => {
    const parts = key.split('.');
    return {
      key,
      moduleKey: parts[0],
      actionKey: parts.at(-1) ?? key,
      label,
      description: label,
      displayOrder,
    };
  },
);
