CREATE TYPE "ProductTypeIdentity" AS ENUM ('PROFESSIONAL_PROGRAM','PROFESSIONAL_DIPLOMA','TRAINING_COURSE');
CREATE TYPE "ProductStatus" AS ENUM ('DRAFT','ACTIVE','HIDDEN','CLOSED','ARCHIVED');
CREATE TYPE "ProductFieldKind" AS ENUM ('NUMBER','OPTION','BOOLEAN','REFERENCE');
CREATE TYPE "ProductBranchRole" AS ENUM ('REGISTRATION','STUDY','GENERAL');
CREATE TYPE "ProductContentKind" AS ENUM ('FAQ','ADMISSION_REQUIREMENT','REQUIRED_DOCUMENT');
CREATE TYPE "ProductAssetKind" AS ENUM ('PRIMARY','GALLERY','BROCHURE','VIDEO');

CREATE TABLE "ProductType" ("id" UUID PRIMARY KEY,"identity" "ProductTypeIdentity" NOT NULL UNIQUE,"nameAr" TEXT NOT NULL,"nameEn" TEXT NOT NULL,"description" TEXT NOT NULL,"status" "EntityStatus" NOT NULL DEFAULT 'ACTIVE',"version" INTEGER NOT NULL DEFAULT 1,"archivedAt" TIMESTAMPTZ,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMPTZ NOT NULL,"createdBy" UUID,"updatedBy" UUID);
CREATE TABLE "ProductTypeField" ("productTypeId" UUID NOT NULL,"key" TEXT NOT NULL,"label" TEXT NOT NULL,"kind" "ProductFieldKind" NOT NULL,"required" BOOLEAN NOT NULL DEFAULT false,"position" INTEGER NOT NULL,PRIMARY KEY("productTypeId","key"),CONSTRAINT "ProductTypeField_productTypeId_fkey" FOREIGN KEY("productTypeId") REFERENCES "ProductType"("id") ON DELETE CASCADE,CONSTRAINT "ProductTypeField_position_positive" CHECK("position">0),CONSTRAINT "ProductTypeField_productTypeId_position_key" UNIQUE("productTypeId","position") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "AcademicProduct" ("id" UUID PRIMARY KEY,"organizationId" UUID NOT NULL,"officialName" TEXT NOT NULL,"nameAr" TEXT NOT NULL,"nameEn" TEXT NOT NULL,"normalizedOfficialName" TEXT NOT NULL,"normalizedNameAr" TEXT NOT NULL,"normalizedNameEn" TEXT NOT NULL,"code" TEXT NOT NULL UNIQUE,"codeLockedAt" TIMESTAMPTZ,"productTypeId" UUID NOT NULL,"categoryId" UUID NOT NULL,"departmentId" UUID,"description" TEXT NOT NULL,"durationValue" INTEGER,"durationUnitId" UUID,"studyModeId" UUID,"numberOfTerms" INTEGER,"numberOfSessions" INTEGER,"numberOfHours" INTEGER,"internshipIncluded" BOOLEAN,"trainingIncluded" BOOLEAN,"finalProjectRequired" BOOLEAN,"certificateIncluded" BOOLEAN NOT NULL DEFAULT false,"instructorEmployeeId" UUID,"salesScript" TEXT,"landingPage" TEXT,"status" "ProductStatus" NOT NULL DEFAULT 'DRAFT',"version" INTEGER NOT NULL DEFAULT 1,"archivedAt" TIMESTAMPTZ,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMPTZ NOT NULL,"createdBy" UUID,"updatedBy" UUID,CONSTRAINT "AcademicProduct_productTypeId_fkey" FOREIGN KEY("productTypeId") REFERENCES "ProductType"("id") ON DELETE RESTRICT,CONSTRAINT "AcademicProduct_positive_academic" CHECK (COALESCE("durationValue",1)>0 AND COALESCE("numberOfTerms",1)>0 AND COALESCE("numberOfSessions",1)>0 AND COALESCE("numberOfHours",1)>0));
CREATE TABLE "ProductPricing" ("productId" UUID PRIMARY KEY,"currency" TEXT NOT NULL,"precision" INTEGER NOT NULL,"basePrice" BIGINT NOT NULL,"registrationFees" BIGINT NOT NULL,"certificateFees" BIGINT NOT NULL,"trainingFees" BIGINT NOT NULL,"cardFees" BIGINT NOT NULL,"examFees" BIGINT NOT NULL,"additionalFees" BIGINT NOT NULL,"discount" BIGINT NOT NULL,"scholarship" BIGINT NOT NULL,"installmentAvailable" BOOLEAN NOT NULL DEFAULT false,CONSTRAINT "ProductPricing_productId_fkey" FOREIGN KEY("productId") REFERENCES "AcademicProduct"("id") ON DELETE CASCADE,CONSTRAINT "ProductPricing_nonnegative" CHECK("precision" BETWEEN 0 AND 6 AND "basePrice">=0 AND "registrationFees">=0 AND "certificateFees">=0 AND "trainingFees">=0 AND "cardFees">=0 AND "examFees">=0 AND "additionalFees">=0 AND "discount">=0 AND "scholarship">=0));
CREATE TABLE "ProductBranchAssignment" ("productId" UUID NOT NULL,"branchId" UUID NOT NULL,"role" "ProductBranchRole" NOT NULL,PRIMARY KEY("productId","branchId","role"),CONSTRAINT "ProductBranchAssignment_productId_fkey" FOREIGN KEY("productId") REFERENCES "AcademicProduct"("id") ON DELETE CASCADE);
CREATE TABLE "ProductContentItem" ("id" UUID PRIMARY KEY,"productId" UUID NOT NULL,"kind" "ProductContentKind" NOT NULL,"title" TEXT NOT NULL,"description" TEXT,"required" BOOLEAN,"position" INTEGER NOT NULL,CONSTRAINT "ProductContentItem_productId_fkey" FOREIGN KEY("productId") REFERENCES "AcademicProduct"("id") ON DELETE CASCADE,CONSTRAINT "ProductContentItem_position_positive" CHECK("position">0),UNIQUE("productId","kind","position"));
CREATE TABLE "ProductAsset" ("id" UUID PRIMARY KEY,"productId" UUID NOT NULL,"kind" "ProductAssetKind" NOT NULL,"fileId" TEXT,"fileName" TEXT,"originalName" TEXT,"mimeType" TEXT,"size" INTEGER,"url" TEXT NOT NULL,"label" TEXT,"position" INTEGER NOT NULL,CONSTRAINT "ProductAsset_productId_fkey" FOREIGN KEY("productId") REFERENCES "AcademicProduct"("id") ON DELETE CASCADE,CONSTRAINT "ProductAsset_position_positive" CHECK("position">0),UNIQUE("productId","kind","position"));
CREATE UNIQUE INDEX "ProductAsset_one_primary" ON "ProductAsset"("productId") WHERE "kind"='PRIMARY';
CREATE TABLE "ProductLifecycleEvent" ("id" UUID PRIMARY KEY,"productId" UUID NOT NULL,"fromStatus" "ProductStatus","toStatus" "ProductStatus" NOT NULL,"reason" TEXT,"actorId" UUID NOT NULL,"resultingVersion" INTEGER NOT NULL,"occurredAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ProductLifecycleEvent_productId_fkey" FOREIGN KEY("productId") REFERENCES "AcademicProduct"("id") ON DELETE RESTRICT);
CREATE INDEX "ProductType_status_updatedAt_idx" ON "ProductType"("status","updatedAt"); CREATE INDEX "AcademicProduct_productTypeId_status_idx" ON "AcademicProduct"("productTypeId","status"); CREATE INDEX "AcademicProduct_categoryId_status_idx" ON "AcademicProduct"("categoryId","status"); CREATE INDEX "AcademicProduct_departmentId_status_idx" ON "AcademicProduct"("departmentId","status"); CREATE INDEX "AcademicProduct_normalizedOfficialName_idx" ON "AcademicProduct"("normalizedOfficialName"); CREATE INDEX "AcademicProduct_normalizedNameAr_idx" ON "AcademicProduct"("normalizedNameAr"); CREATE INDEX "AcademicProduct_normalizedNameEn_idx" ON "AcademicProduct"("normalizedNameEn"); CREATE INDEX "AcademicProduct_updatedAt_idx" ON "AcademicProduct"("updatedAt"); CREATE INDEX "ProductBranchAssignment_branchId_role_idx" ON "ProductBranchAssignment"("branchId","role"); CREATE INDEX "ProductContentItem_productId_kind_idx" ON "ProductContentItem"("productId","kind"); CREATE INDEX "ProductAsset_productId_kind_idx" ON "ProductAsset"("productId","kind"); CREATE INDEX "ProductLifecycleEvent_productId_occurredAt_idx" ON "ProductLifecycleEvent"("productId","occurredAt");
