-- DropIndex
DROP INDEX "knowledge_chunk_embedding_idx";

-- NOTE: this migration was generated by `prisma migrate dev`, which cannot see
-- the HNSW index and therefore treats it as drift. It should not have been
-- applied. 20260910213000_restore_knowledge_chunk_hnsw puts the index back.
