"use client"
import { Controller, useFieldArray, useFormContext } from "react-hook-form"
import { ArrowDown, ArrowUp, Plus, Trash2 } from "lucide-react"
import { Button } from "@workspace/ui/components/button"
import { RichTextField } from "@/shared/components/forms/rich-text-field"
import type { ProductFormValues } from "../schemas/product-schema"

type CollectionName = "content.faqs" | "content.admissionRequirements" | "content.requiredDocuments"
function ContentRepeater({ name, title, addLabel }: { name: CollectionName; title: string; addLabel: string }) { const { control, register } = useFormContext<ProductFormValues>(); const fields = useFieldArray<ProductFormValues, CollectionName>({ control, name }); return <fieldset className="space-y-3 rounded-lg border p-4"><legend className="px-2 font-medium">{title}</legend>{fields.fields.map((field, index) => <div key={field.id} className="grid items-start gap-2 sm:grid-cols-[1fr_auto]"><label className="space-y-1 text-sm"><span>{title} {index + 1}</span><input {...register(`${name}.${index}.title`)} className="h-10 w-full rounded-lg border border-input bg-background px-3" /></label><div className="flex gap-1 pt-6"><Button type="button" size="icon-sm" variant="ghost" aria-label="تحريك لأعلى" disabled={index === 0} onClick={() => fields.swap(index, index - 1)}><ArrowUp /></Button><Button type="button" size="icon-sm" variant="ghost" aria-label="تحريك لأسفل" disabled={index === fields.fields.length - 1} onClick={() => fields.swap(index, index + 1)}><ArrowDown /></Button><Button type="button" size="icon-sm" variant="destructive" aria-label="إزالة" onClick={() => fields.remove(index)}><Trash2 /></Button></div></div>)}<Button type="button" variant="outline" onClick={() => fields.append({ id: crypto.randomUUID(), title: "", position: fields.fields.length })}><Plus />{addLabel}</Button></fieldset> }
export function ProductSalesSection() { const { control } = useFormContext<ProductFormValues>(); return <div className="space-y-5"><Controller control={control} name="content.salesScript" render={({ field }) => <RichTextField label="النص البيعي" value={field.value} onChange={field.onChange} />} /><div className="grid gap-5 xl:grid-cols-3"><ContentRepeater name="content.faqs" title="الأسئلة الشائعة" addLabel="إضافة سؤال" /><ContentRepeater name="content.admissionRequirements" title="متطلبات القبول" addLabel="إضافة متطلب" /><ContentRepeater name="content.requiredDocuments" title="المستندات المطلوبة" addLabel="إضافة مستند" /></div></div> }
