import {
  Blocks,
  BookOpen,
  Boxes,
  Building2,
  CalendarDays,
  CalendarRange,
  ClipboardCheck,
  FolderTree,
  Gauge,
  GitBranch,
  GraduationCap,
  ReceiptText,
  Wallet,
  KeyRound,
  LibraryBig,
  MessagesSquare,
  Tickets,
  MapPin,
  Settings2,
  ShieldCheck,
  SlidersHorizontal,
  UsersRound,
  type LucideIcon,
} from "lucide-react"

export const iconRegistry = {
  dashboard: Gauge,
  foundation: Blocks,
  settings: Settings2,
  organization: Building2,
  branches: GitBranch,
  departments: MapPin,
  academicYears: CalendarRange,
  academicTerms: CalendarDays,
  users: UsersRound,
  roles: ShieldCheck,
  permissions: KeyRound,
  general: SlidersHorizontal,
  catalog: LibraryBig,
  products: BookOpen,
  productTypes: Boxes,
  categories: FolderTree,
  admissions: ClipboardCheck,
  students: GraduationCap,
  finance: Wallet,
  accounting: ReceiptText,
  inbox: MessagesSquare,
  tickets: Tickets,
} satisfies Record<string, LucideIcon>
export type NavigationIconKey = keyof typeof iconRegistry
