CREATE TYPE "TicketStatus" AS ENUM ('BACKLOG','TODO','IN_PROGRESS','WAITING','REVIEW','DONE','ARCHIVED');
CREATE TYPE "TicketPriority" AS ENUM ('LOW','MEDIUM','HIGH','CRITICAL');
CREATE TABLE "TicketTeam" ("id" UUID PRIMARY KEY, "organizationId" UUID NOT NULL, "name" TEXT NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "TicketTeamMembership" ("teamId" UUID NOT NULL, "employeeId" UUID NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, PRIMARY KEY ("teamId","employeeId"), CONSTRAINT "TicketTeamMembership_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "TicketTeam"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "Ticket" ("id" UUID PRIMARY KEY, "organizationId" UUID NOT NULL, "number" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "status" "TicketStatus" NOT NULL DEFAULT 'BACKLOG', "lastActiveStatus" "TicketStatus" NOT NULL DEFAULT 'BACKLOG', "priority" "TicketPriority" NOT NULL DEFAULT 'MEDIUM', "departmentId" UUID NOT NULL, "branchId" UUID, "teamId" UUID, "employeeId" UUID, "customerId" UUID, "studentId" UUID, "conversationId" UUID, "dueAt" TIMESTAMPTZ, "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], "completedAt" TIMESTAMPTZ, "archivedAt" TIMESTAMPTZ, "deletedAt" TIMESTAMPTZ, "version" INTEGER NOT NULL DEFAULT 1, "activitySequence" INTEGER NOT NULL DEFAULT 0, "createdBy" UUID NOT NULL, "updatedBy" UUID NOT NULL, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ NOT NULL);
ALTER TABLE "Ticket" ADD COLUMN "priorityRank" INTEGER NOT NULL DEFAULT 2;
CREATE TABLE "TicketComment" ("id" UUID PRIMARY KEY, "ticketId" UUID NOT NULL, "authorId" UUID NOT NULL, "authorName" TEXT NOT NULL, "message" TEXT NOT NULL, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ, "deletedAt" TIMESTAMPTZ, CONSTRAINT "TicketComment_ticketId_fkey" FOREIGN KEY ("ticketId") REFERENCES "Ticket"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE TABLE "TicketActivity" ("id" UUID PRIMARY KEY, "ticketId" UUID NOT NULL, "sequence" INTEGER NOT NULL, "type" TEXT NOT NULL, "actorId" UUID NOT NULL, "actorName" TEXT NOT NULL, "message" TEXT NOT NULL, "payload" JSONB NOT NULL, "occurredAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "TicketActivity_ticketId_fkey" FOREIGN KEY ("ticketId") REFERENCES "Ticket"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE TABLE "TicketAttachment" ("id" UUID PRIMARY KEY, "ticketId" UUID NOT NULL, "name" TEXT NOT NULL, "mimeType" TEXT NOT NULL, "sizeBytes" INTEGER NOT NULL, "storageId" TEXT NOT NULL, "storageName" TEXT NOT NULL, "uploadedBy" UUID NOT NULL, "uploadedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "uploadKey" TEXT, CONSTRAINT "TicketAttachment_ticketId_fkey" FOREIGN KEY ("ticketId") REFERENCES "Ticket"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE TABLE "TicketCounter" ("organizationId" UUID PRIMARY KEY, "nextNumber" INTEGER NOT NULL DEFAULT 1001);
CREATE UNIQUE INDEX "TicketTeam_organizationId_name_key" ON "TicketTeam"("organizationId","name");
CREATE INDEX "TicketTeam_organizationId_active_idx" ON "TicketTeam"("organizationId","active");
CREATE INDEX "TicketTeamMembership_employeeId_active_idx" ON "TicketTeamMembership"("employeeId","active");
CREATE UNIQUE INDEX "Ticket_organizationId_number_key" ON "Ticket"("organizationId","number");
CREATE INDEX "Ticket_organizationId_archivedAt_status_updatedAt_id_idx" ON "Ticket"("organizationId","archivedAt","status","updatedAt" DESC,"id");
CREATE INDEX "Ticket_organizationId_employeeId_status_idx" ON "Ticket"("organizationId","employeeId","status");
CREATE INDEX "Ticket_organizationId_teamId_status_idx" ON "Ticket"("organizationId","teamId","status");
CREATE INDEX "Ticket_organizationId_branchId_status_idx" ON "Ticket"("organizationId","branchId","status");
CREATE INDEX "Ticket_organizationId_archivedAt_priorityRank_updatedAt_id_idx" ON "Ticket"("organizationId","archivedAt","priorityRank" DESC,"updatedAt" DESC,"id");
CREATE INDEX "TicketComment_ticketId_createdAt_id_idx" ON "TicketComment"("ticketId","createdAt","id");
CREATE UNIQUE INDEX "TicketActivity_ticketId_sequence_key" ON "TicketActivity"("ticketId","sequence");
CREATE INDEX "TicketActivity_ticketId_sequence_idx" ON "TicketActivity"("ticketId","sequence");
CREATE UNIQUE INDEX "TicketAttachment_ticketId_uploadKey_key" ON "TicketAttachment"("ticketId","uploadKey");
CREATE INDEX "TicketAttachment_ticketId_uploadedAt_id_idx" ON "TicketAttachment"("ticketId","uploadedAt","id");
